task:
  matrix:
    - name: Test (JDK 17)
      container:
        image: gradle:7-jdk11
  gradle_cache:
    folder: ~/.gradle/caches
  check_script: gradle check --stacktrace
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - rm -f ~/.gradle/caches/user-id.txt
    - rm -f ~/.gradle/caches/journal-1/file-access.bin
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
  on_failure:
    junit_artifacts:
      path: "**/test-results/**/*.xml"
      format: junit
