language: java
sudo: false
jdk:
  - oraclejdk8

before_cache:
  - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
  - rm -f ~/.gradle/caches/user-id.txt
  - find ~/.gradle/caches/ -name "*.lock" -type f -delete

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: ./gradlew check